media: images

content:
  - name: config
    label: Saidi seaded
    type: file
    path: _config.yml
    fields:
      - name: title
        type: string
        label: Saidi nimi
      - name: description
        type: text
        label: Kirjeldus
      - name: email
        type: string
        label: E-post
      - name: phone
        type: string
        label: Telefon

  - name: home
    label: Avaleht
    type: file
    path: index.markdown
    fields:
      - name: title
        type: string
        label: Pealkiri
      - name: description
        type: text
        label: Meta kirjeldus

  - name: tooted
    label: Tooted ja kategooriad
    type: collection
    path: _products
    new_item_key: toode
    filename: "{primary}.md"
    create:
      path: _products
      extra_inputs:
        - name: type
          label: Tüüp
          type: select
          options:
            values:
              - label: Kategooria
                value: category
              - label: Toode
                value: product
      front_matter:
        layout: product
        title: "Uus toode"
        description: ""
    structure:
      type: tree
    view:
      primary: title
    fields:
      - name: layout
        type: hidden
        default: category
      - name: title
        type: string
        label: Pealkiri
      - name: description
        type: text
        label: Kirjeldus
      - name: permalink
        type: string
        label: Püsiviide (vajalik ainult kategoorial)
      - name: hidden
        type: boolean
        label: Peidetud
      - name: body
        type: rich-text
        label: Sisu
