media: images

content:
  - name: config
    label: Saidi seaded
    type: file
    path: _config.yml
    fields:
      - name: title
        type: string
        label: Saidi nimi
      - name: description
        type: text
        label: Kirjeldus
      - name: email
        type: string
        label: E-post
      - name: phone
        type: string
        label: Telefon

  - name: home
    label: Avaleht
    type: file
    path: index.markdown
    fields:
      - name: title
        type: string
        label: Pealkiri
      - name: description
        type: text
        label: Meta kirjeldus

  - name: kategooriad
    label: Kategooriad
    type: collection
    path: _products
    glob: "**/index.md"
    new_item_key: category
    create:
      path: _products
      filename: "{key}/index.md"
      front_matter:
        layout: category
        title: "Uus kategooria"
        description: ""
        permalink: "/category/{key}/"
    fields:
      - name: layout
        type: hidden
        default: category
      - name: title
        type: string
        label: Pealkiri
      - name: description
        type: text
        label: Kirjeldus
      - name: permalink
        type: string
        label: Püsiviide
      - name: hidden
        type: boolean
        label: Peidetud

  - name: tooted
    label: Tooted
    type: collection
    path: _products
    exclude:
      - "**/index.md"
    new_item_key: product
    create:
      path: _products
      glob: "{category}/*.md"
      filename: "{key}.md"
      extra_inputs:
        - name: category
          label: Kategooria
          type: select
          options:
            values: _products/*/
      front_matter:
        layout: product
        title: "Uus toode"
        description: ""
    view:
      primary: title
    fields:
      - name: layout
        type: hidden
        default: product
      - name: title
        type: string
        label: Pealkiri
      - name: description
        type: text
        label: Kirjeldus
      - name: category_title
        type: string
        label: Kategooria nimi
      - name: category_url
        type: string
        label: Kategooria URL
      - name: permalink
        type: string
        label: Püsiviide
      - name: body
        type: rich-text
        label: Sisu
