media: images

content:
  - name: config
    label: Saidi seaded
    type: file
    path: _config.yml
    fields:
      - name: title
        type: string
        label: Saidi nimi
      - name: description
        type: text
        label: Kirjeldus
      - name: email
        type: string
        label: E-post
      - name: phone
        type: string
        label: Telefon
      - name: locations
        type: object
        label: Asukohad
        fields:
          - name: tehnika
            type: string
            label: Tehnika
          - name: tellingud
            type: string
            label: Tellingud ja piirdeaiad

  - name: home
    label: Avaleht
    type: file
    path: index.md
    fields:
      - name: title
        type: string
        label: Pealkiri
      - name: description
        type: text
        label: Meta kirjeldus

  - name: lehed
    label: Lehed
    type: collection
    path: _pages
    filename: "{primary}.md"
    exclude: ["products/*"]
    view:
      primary: title
    fields:
      - name: layout
        type: string
        hidden: true
      - name: title
        type: string
        label: Pealkiri
      - name: description
        type: text
        label: Kirjeldus
      - name: image
        type: image
        label: Pilt
      - name: category
        type: string
        label: Kategooria
      - name: categories
        type: list
        label: Kategooriad
      - name: children
        type: list
        label: Alamlehed
      - name: permalink
        type: string
        label: Püsiviide
      - name: body
        type: rich-text
        label: Sisu

  - name: tooted
    label: Tooted
    type: collection
    path: _pages/products
    filename: "{primary}.md"
    view:
      primary: title
    fields:
      - name: title
        type: string
        label: Pealkiri
      - name: description
        type: text
        label: Kirjeldus
      - name: category
        type: string
        label: Kategooria
      - name: image
        type: image
        label: Pilt
      - name: permalink
        type: string
        label: Püsiviide
      - name: additionalEquipment
        type: list
        label: Lisaseadmed
      - name: body
        type: rich-text
        label: Sisu
