title: SoMi-Rent
description: Masinate ja seadmete rent kogu Eestis.
url: "https://somirent.ee"
email: tarmosokolov@gmail.com
phone: +372 55991560
permalink: pretty

languages:
  - et
  - ru

exclude:
  - AGENTS.md
  - vendor
  - node_modules
  - .bundle
  - .idea
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - tailwind.config.js
  - build.sh
  - LICENCE

plugins:
  - jekyll-sitemap

locations:
  tehnika: Saku vald, Tõdva küla
  tellingud: Suur-Sõjamäe 25a

include:
  - _pages

defaults:
  - scope:
      path: "_pages/et/products"
    values:
      layout: product
      lang: et
  - scope:
      path: "_pages/ru/products"
    values:
      layout: product
      lang: ru
  - scope:
      path: "_pages/et"
    values:
      layout: page
      lang: et
  - scope:
      path: "_pages/ru"
    values:
      layout: page
      lang: ru
