title: SoMi-Rent
description: Masinate ja seadmete rent kogu Eestis.
url: "https://demo-rendiportaal.pikker.dev"
email: tarmosokolov@gmail.com
phone: +372 55991560
permalink: pretty

exclude:
  - AGENTS.md
  - vendor
  - node_modules
  - .bundle
  - .idea
  - Gemfile
  - Gemfile.lock
  - package.json
  - package-lock.json
  - tailwind.config.js
  - build.sh
  - LICENCE

plugins:
  - jekyll-sitemap

locations:
  tehnika: Saku vald, Tõdva küla
  tellingud: Suur-Sõjamäe 25

navigation:
  - title: Rendi avant
    url: /products/avant-laadur-530/
    children:
      - title: Avant 530
        url: /products/avant-laadur-530/
  - title: Haljastusteenused
    url: /haljastusteenused/
    children:
      - title: Pinnasetööd
        url: /products/pinnasetood/
      - title: Haljastusteenused
        url: /products/haljastusteenused/
      - title: Lumelükkamine
        url: /products/lumelukkamine/
  - title: Teenused
    url: /teenused/
    children:
      - title: Avant juhiga
        url: /products/avant-juhiga/
      - title: Avant juhita
        url: /products/avant-juhita/
  - title: Tellingud ja piirdeaiad
    url: /tellingud-ja-piirdeaiad/
    children:
      - title: Raamtellingud
        url: /products/tellingud/
      - title: Piirdeaiad
        url: /products/piirdeaiad/
  - title: Haagise rent
    url: /haagise-rent/
    children:
      - title: TikiTreileri Kerghaagis
        url: /products/tiki-kerghaagis-kaanega/
      - title: Autoülekande haagis
        url: /products/ap2600-drb/
  - title: Kontakt
    url: /kontakt/
  - title: Saada päring
    url: /paring/
    button: true



footer_links:
  - title: Rendi avant
    url: /products/avant-laadur-530/
  - title: Tellingud ja piirdeaiad
    url: /tellingud-ja-piirdeaiad/
  - title: Saada päring
    url: /paring/
  - title: Kontakt
    url: /kontakt/

include:
  - _pages

defaults:
  - scope:
      path: "_pages/products"
    values:
      layout: product
  - scope:
      path: "_pages"
    values:
      layout: page
