title: SoMi-Rent
description: Masinate ja seadmete rent kogu Eestis.
email: rihard@pikker.dev
phone: +372 55991560
permalink: pretty

include:
  - _pages

defaults:
  - scope:
      path: "_pages/products"
    values:
      layout: product
  - scope:
      path: "_pages"
    values:
      layout: page
